// <auto-generated />
namespace ControleCustos.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdicionarastabelasUnidadeTecnicaCustoeColaboradores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionarastabelasUnidadeTecnicaCustoeColaboradores));
        
        string IMigrationMetadata.Id
        {
            get { return "201612201841061_Adicionar as tabelas UnidadeTecnica, Custo e Colaboradores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
