// <auto-generated />
namespace ControleCustos.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RetirarcamposnaousadoseadicionarContaemCusto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RetirarcamposnaousadoseadicionarContaemCusto));
        
        string IMigrationMetadata.Id
        {
            get { return "201612201940562_Retirar campos nao usados e adicionar Conta em Custo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
